Enforcing usage of Key Vaults in Add/Update monitoring virtual machine workbooks.
microsoft/Application-Insights-Workbooks pull request #1691
Opened 2021-11-04 19:18 UTC by bhsu-ms

## PR Checklist
Enforcing usage of Key Vaults in monitoring vm config related workbooks due to security concerns. With this update, users cannot add/update monitoring vm config without giving access to Key Vaults. Added an informational banner asking user to reference passwords from Key Vaults and two error banners when access is not provided.
* [x] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.

### If adding or updating templates:
* [x] post a screenshot of templates and/or gallery changes
* [x] ensure your template has a corresponding gallery entry in the gallery folder
* [x] grep `/subscription/` and ensure that your parameters don't have any hardcoded resourceIds __or they will fail PR validation__
* [x] remove `fallbackResourceIds` and `fromTemplateId` fields from your template workbook __or they will fail PR validation__
![image](https://user-images.githubusercontent.com/72472578/140404708-778a6db5-c242-470e-9495-1fae660fba9c.png)
![image](https://user-images.githubusercontent.com/72472578/140404818-a0cb6f24-12c7-4db5-a642-e1452692f1e4.png)
link to workbooks: https://ms.portal.azure.com/?feature.includePreviewTemplates=true&feature.localtemplates=true&feature.workloadinsights=true&feature.workbookGalleryRedirect=https%3A%2F%2Freadablesecondaries.blob.core.windows.net%2Fazure-monitor-workbook-templates%2Fpackage#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/sqlWorkloadInsights

2021-11-04 21:22 UTC, masree approved these changes

2021-11-05 20:47 UTC, dimitri-furman requested changes
Suggested tweaks to user-visible messages

2021-11-05 20:47 UTC, dimitri-furman commented on Workbooks/Workloads/SQL/Add monitoring virtual machine/Add monitoring virtual machine.workbook
> +              "json": "#### Enable access to Azure Key Vaults\nPlease provide access to the virtual machine from the Key Vaults referenced in the connection strings via Managed Service Identity."
proposed message, for clarity: `#### Enable access to Azure Key Vault\nUse Key Vault access policy to provide the Get Secret permission for all key vaults referenced in configuration. Permission must be provided to the Managed Service Identity of the monitoring virtual machine.`

2021-11-05 20:47 UTC, dimitri-furman commented on Workbooks/Workloads/SQL/Add monitoring virtual machine/Add monitoring virtual machine.workbook
> +              "json": "Please provide access to the Key Vaults",
`Please provide access to Key Vault`

2021-11-05 20:47 UTC, dimitri-furman commented on Workbooks/Workloads/SQL/Add monitoring virtual machine/Add monitoring virtual machine.workbook
> +              "json": "Please provide access to the Key Vaults",
`Please provide access to Key Vault`

2021-11-05 20:47 UTC, dimitri-furman commented on Workbooks/Workloads/Update monitoring vm config/Update monitoring vm config.workbook
> +        "json": "Please reference passwords from Key Vaults.",
`Please reference passwords stored as Key Vault secrets.`

2021-11-05 20:47 UTC, dimitri-furman commented on Workbooks/Workloads/Update monitoring vm config/Update monitoring vm config.workbook
> +        "json": "#### Enable access to Azure Key Vaults\nPlease provide access to the virtual machine from the Key Vaults referenced in the connection strings via Managed Service Identity."
`#### Enable access to Azure Key Vault\nUse Key Vault access policy to provide the Get Secret permission for all key vaults referenced in configuration. Permission must be provided to the Managed Service Identity of the monitoring virtual machine.`

2021-11-05 20:47 UTC, dimitri-furman commented on Workbooks/Workloads/Update monitoring vm config/Update monitoring vm config.workbook
> +        "json": "Please provide access to the Key Vaults",
`Please provide access to Key Vault`

2021-11-05 20:47 UTC, dimitri-furman commented on Workbooks/Workloads/Update monitoring vm config/Update monitoring vm config.workbook
> +        "json": "Please provide access to the Key Vaults",
`Please provide access to Key Vault`

2021-11-08 18:50 UTC, gardnerjr reviewed
did you explicitly request review from the workbooks team or is it because of CODEOWNERS says we own the files (the default state?)  If you own these files, you should add your github team to the CODEOWNERS file for this path, so that it doesn't require workbooks team to review your content.

2021-11-08 18:53 UTC, gardnerjr commented
for the code owners part, it might just be a syntax issue in the `CODEOWNERS` file that's not catching these.
codeowners has:

```
/Workbooks/Workloads/SQL** @microsoft/sqlexternalmonitoring
```

but it looks like it is missing a trailing `/` to mark it as "Everything inside SQL folder" instead of "every file with SQL in the name" like it is now.

looks like it should be:
```
/Workbooks/Workloads/SQL/** @microsoft/sqlexternalmonitoring
```

2021-11-10 21:06 UTC, dimitri-furman approved these changes

2021-11-10 21:21 UTC, bhsu-ms commented
> for the code owners part, it might just be a syntax issue in the `CODEOWNERS` file that's not catching these. codeowners has:
> 
> ```
> /Workbooks/Workloads/SQL** @microsoft/sqlexternalmonitoring
> ```
> 
> but it looks like it is missing a trailing `/` to mark it as "Everything inside SQL folder" instead of "every file with SQL in the name" like it is now.
> 
> looks like it should be:
> 
> ```
> /Workbooks/Workloads/SQL/** @microsoft/sqlexternalmonitoring
> ```

Hi John, thanks for spotting that.

I have updated the CODEOWNERS file accordingly.

2021-11-10 22:00 UTC, gardnerjr approved these changes
haven't really  validated *content*, but have looked at codeowners and general

2021-11-10 23:36 UTC, merged