Mpbastos/avdiupdate
microsoft/Application-Insights-Workbooks pull request #2807
Opened 2024-10-14 17:33 UTC by mpbastos

- Add case insensitive regex on the AssignedDCR parameter to select the default DCR.
- Upate poolla to use ARG query on all subscriptions instead of selected.

[Private Branch](https://portal.azure.com/?feature.workbookGalleryBranch=mpbastos/avdiupdate)

2024-10-14 18:08 UTC, xiangtin approved these changes

2024-10-14 18:08 UTC, xiangtin commented
Need to update the version number.

2024-10-14 22:14 UTC, mike-mo requested changes
Need version number update

2024-10-15 19:26 UTC, mike-mo approved these changes

2024-10-16 15:58 UTC, merged